<?php

namespace VG\StandardCodeTestBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VarnishLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VarnishLogRepository extends EntityRepository
{
}
